networks:
  proxy:
    external: true

services:
  # A simple HTML page to display links to all the services.
  # Can be used for dashboards, landing pages, etc.
  # Set NGINX_HTML to specify the HTML directory path
  # Set NGINX_ROUTER_RULE to customize routing (default: Host(`<stack-name>.${DOMAIN}`))
  # 
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:alpine
    volumes:
      - ${NGINX_HTML:-../../config/nginx}:/usr/share/nginx/html:ro,z
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.10"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.${NGINX_CONTAINER_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${NGINX_CONTAINER_NAME}.rule=${NGINX_ROUTER_RULE:-Host(`${NGINX_CONTAINER_NAME}.${DOMAIN}`)}"
      - "traefik.http.routers.${NGINX_CONTAINER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NGINX_CONTAINER_NAME}.tls=true"
      - "traefik.http.routers.${NGINX_CONTAINER_NAME}.tls.certresolver=myresolver"
