name: ${PROJECT}

services:
  # Watchtower is a process for automating Docker container base image updates.
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${WATCHTOWER_CPU_LIMIT:-0.5}
          memory: ${WATCHTOWER_MEM_LIMIT:-256M}
    security_opt:
      - no-new-privileges:true
      - label=type:container_runtime_t # Required for SELinux to access docker.sock
    command: --interval 86400 --cleanup
