networks:
  proxy:
    external: true

services:
  # Home Assistant is a home automation platform that focuses on privacy and local control.
  # It allows you to control all your devices from a single, mobile-friendly interface.
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ${VOLUMES_PATH}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Zigbee USB dongle
    environment:
      - TZ=${TIMEZONE}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: "2"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.home-assistant.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.home-assistant.entrypoints=websecure"
      - "traefik.http.routers.home-assistant.tls=true"
      - "traefik.http.routers.home-assistant.tls.certresolver=myresolver"
